create extension if not exists pgcrypto;
create type public.member_role as enum ('owner','member');
create type public.member_status as enum ('invited','active','inactive');
create type public.movement_direction as enum ('in','out');

create table public.organizations(id uuid primary key default gen_random_uuid(),name text not null,slug text not null unique,status text not null default 'active',settings jsonb not null default '{}',created_at timestamptz not null default now(),updated_at timestamptz not null default now());
create table public.profiles(id uuid primary key references auth.users(id) on delete cascade,display_name text,email text not null,created_at timestamptz not null default now(),updated_at timestamptz not null default now());
create table public.memberships(id uuid primary key default gen_random_uuid(),organization_id uuid not null references public.organizations(id) on delete cascade,profile_id uuid references public.profiles(id) on delete cascade,email text not null,role public.member_role not null default 'member',status public.member_status not null default 'invited',invited_at timestamptz not null default now(),activated_at timestamptz,unique(organization_id,email),unique(organization_id,profile_id));

create or replace function public.is_org_member(org_id uuid) returns boolean language sql stable security definer set search_path=public as $$select exists(select 1 from memberships where organization_id=org_id and profile_id=auth.uid() and status='active')$$;
create or replace function public.is_org_owner(org_id uuid) returns boolean language sql stable security definer set search_path=public as $$select exists(select 1 from memberships where organization_id=org_id and profile_id=auth.uid() and status='active' and role='owner')$$;

create table public.products(id uuid primary key default gen_random_uuid(),organization_id uuid not null references public.organizations(id) on delete cascade,name text not null,occasion text,grams numeric(12,3) not null default 0,print_minutes numeric(12,2) not null default 0,work_minutes numeric(12,2) not null default 0,supplies numeric(12,2) not null default 0,packaging numeric(12,2) not null default 0,multiplier numeric(6,2) not null default 3,model_license text,active boolean not null default true,created_by uuid references public.profiles(id),updated_by uuid references public.profiles(id),created_at timestamptz not null default now(),updated_at timestamptz not null default now());
create table public.inventory_items(id uuid primary key default gen_random_uuid(),organization_id uuid not null references public.organizations(id) on delete cascade,name text not null,type text not null,category text,color text,unit text not null,quantity numeric(14,3) not null default 0,minimum numeric(14,3) not null default 0,unit_cost numeric(12,2) not null default 0,created_by uuid references public.profiles(id),updated_by uuid references public.profiles(id),created_at timestamptz not null default now(),updated_at timestamptz not null default now());
create table public.clients(id uuid primary key default gen_random_uuid(),organization_id uuid not null references public.organizations(id) on delete cascade,name text not null,phone text,email text,instagram text,notes text,created_by uuid references public.profiles(id),updated_by uuid references public.profiles(id),created_at timestamptz not null default now(),updated_at timestamptz not null default now());
create table public.orders(id uuid primary key default gen_random_uuid(),organization_id uuid not null references public.organizations(id) on delete cascade,code text not null,client_id uuid references public.clients(id),status text not null default 'Orçamento enviado',event_date date,delivery_date date,gross numeric(12,2) not null default 0,discount numeric(12,2) not null default 0,total numeric(12,2) not null default 0,paid numeric(12,2) not null default 0,balance numeric(12,2) not null default 0,cost numeric(12,2) not null default 0,profit numeric(12,2) not null default 0,notes text,created_by uuid references public.profiles(id),updated_by uuid references public.profiles(id),created_at timestamptz not null default now(),updated_at timestamptz not null default now(),unique(organization_id,code));
create table public.order_items(id uuid primary key default gen_random_uuid(),organization_id uuid not null references public.organizations(id) on delete cascade,order_id uuid not null references public.orders(id) on delete cascade,product_id uuid references public.products(id),product_name text not null,quantity numeric(12,3) not null,individualized boolean not null default false,unit_price numeric(12,2) not null,unit_cost numeric(12,2) not null,discount_rate numeric(6,4) not null default 0,total numeric(12,2) not null,cost numeric(12,2) not null,created_at timestamptz not null default now());
create table public.cash_movements(id uuid primary key default gen_random_uuid(),organization_id uuid not null references public.organizations(id) on delete cascade,date date not null,direction public.movement_direction not null,category text not null,description text not null,amount numeric(12,2) not null check(amount>=0),order_id uuid references public.orders(id),created_by uuid references public.profiles(id),created_at timestamptz not null default now());
create table public.payments(id uuid primary key default gen_random_uuid(),organization_id uuid not null references public.organizations(id) on delete cascade,order_id uuid not null references public.orders(id),date date not null,amount numeric(12,2) not null check(amount>0),method text not null,cash_movement_id uuid unique references public.cash_movements(id),reversed_at timestamptz,reversed_by uuid references public.profiles(id),created_by uuid references public.profiles(id),created_at timestamptz not null default now());
create table public.inventory_movements(id uuid primary key default gen_random_uuid(),organization_id uuid not null references public.organizations(id) on delete cascade,item_id uuid not null references public.inventory_items(id),direction public.movement_direction not null,quantity numeric(14,3) not null check(quantity>0),reason text not null,order_id uuid references public.orders(id),created_by uuid references public.profiles(id),created_at timestamptz not null default now());
create table public.production_jobs(id uuid primary key default gen_random_uuid(),organization_id uuid not null references public.organizations(id) on delete cascade,order_id uuid references public.orders(id),order_item_id uuid references public.order_items(id),name text not null,kind text not null check(kind in ('order','portfolio','stock')),event_date date,quantity numeric(12,3) not null default 1,planned_hours numeric(12,2) not null default 0,status text not null default 'Planejado',failures numeric(12,3) not null default 0,manual_position integer,created_by uuid references public.profiles(id),updated_by uuid references public.profiles(id),created_at timestamptz not null default now(),updated_at timestamptz not null default now());
create table public.content_items(id uuid primary key default gen_random_uuid(),organization_id uuid not null references public.organizations(id) on delete cascade,title text not null,week integer,format text,cta text,publish_date date,status text not null default 'Ideia',reach integer not null default 0,saves integer not null default 0,directs integer not null default 0,created_by uuid references public.profiles(id),updated_by uuid references public.profiles(id),created_at timestamptz not null default now(),updated_at timestamptz not null default now());
create table public.partners(id uuid primary key default gen_random_uuid(),organization_id uuid not null references public.organizations(id) on delete cascade,name text not null,type text,contact text,status text not null default 'A visitar',last_contact date,notes text,created_by uuid references public.profiles(id),updated_by uuid references public.profiles(id),created_at timestamptz not null default now(),updated_at timestamptz not null default now());
create table public.audit_events(id bigint generated always as identity primary key,organization_id uuid not null references public.organizations(id) on delete cascade,actor_id uuid references public.profiles(id),action text not null,entity_type text not null,entity_id text,summary text,before_data jsonb,after_data jsonb,created_at timestamptz not null default now());

do $$ declare t text; begin foreach t in array array['organizations','products','inventory_items','inventory_movements','clients','orders','order_items','payments','production_jobs','content_items','partners','cash_movements','audit_events'] loop execute format('alter table public.%I enable row level security',t); end loop; end $$;
create policy org_select on public.organizations for select using(public.is_org_member(id));
create policy org_owner_update on public.organizations for update using(public.is_org_owner(id));
do $$ declare t text; begin foreach t in array array['products','inventory_items','inventory_movements','clients','orders','order_items','payments','production_jobs','content_items','partners','cash_movements'] loop execute format('create policy member_all on public.%I for all using(public.is_org_member(organization_id)) with check(public.is_org_member(organization_id))',t); end loop; end $$;
create policy audit_select on public.audit_events for select using(public.is_org_member(organization_id));create policy audit_insert on public.audit_events for insert with check(public.is_org_member(organization_id));
alter table public.memberships enable row level security;create policy membership_select on public.memberships for select using(public.is_org_member(organization_id));create policy membership_owner_write on public.memberships for all using(public.is_org_owner(organization_id)) with check(public.is_org_owner(organization_id));
alter table public.profiles enable row level security;create policy profile_self on public.profiles for select using(id=auth.uid());create policy profile_self_update on public.profiles for update using(id=auth.uid());
create index on public.orders(organization_id,event_date);create index on public.production_jobs(organization_id,status,event_date);create index on public.cash_movements(organization_id,date);create index on public.audit_events(organization_id,created_at desc);
