create or replace function public.create_order_with_items(p_organization_id uuid,p_code text,p_client_id uuid,p_status text,p_event_date date,p_delivery_date date,p_notes text,p_totals jsonb,p_items jsonb) returns uuid language plpgsql security invoker as $$declare new_id uuid; item jsonb;begin
if not public.is_org_member(p_organization_id) then raise exception 'unauthorized';end if;
insert into orders(organization_id,code,client_id,status,event_date,delivery_date,gross,discount,total,paid,balance,cost,profit,notes,created_by,updated_by) values(p_organization_id,p_code,p_client_id,p_status,p_event_date,p_delivery_date,(p_totals->>'gross')::numeric,(p_totals->>'discount')::numeric,(p_totals->>'total')::numeric,0,(p_totals->>'total')::numeric,(p_totals->>'cost')::numeric,(p_totals->>'profit')::numeric,p_notes,auth.uid(),auth.uid()) returning id into new_id;
for item in select * from jsonb_array_elements(p_items) loop insert into order_items(organization_id,order_id,product_id,product_name,quantity,individualized,unit_price,unit_cost,discount_rate,total,cost) values(p_organization_id,new_id,(item->>'product_id')::uuid,item->>'product_name',(item->>'quantity')::numeric,(item->>'individualized')::boolean,(item->>'unit_price')::numeric,(item->>'unit_cost')::numeric,(item->>'discount_rate')::numeric,(item->>'total')::numeric,(item->>'cost')::numeric);end loop;
insert into audit_events(organization_id,actor_id,action,entity_type,entity_id,summary,after_data)values(p_organization_id,auth.uid(),'create','orders',new_id::text,'Criou pedido '||p_code,p_totals);return new_id;end$$;

create or replace function public.record_order_payment(p_organization_id uuid,p_order_id uuid,p_date date,p_amount numeric,p_method text) returns uuid language plpgsql security invoker as $$declare cash_id uuid;payment_id uuid;order_row orders%rowtype;begin
if not public.is_org_member(p_organization_id) then raise exception 'unauthorized';end if;select * into order_row from orders where id=p_order_id and organization_id=p_organization_id for update;if not found then raise exception 'order_not_found';end if;if p_amount<=0 or p_amount>order_row.balance then raise exception 'invalid_amount';end if;
insert into cash_movements(organization_id,date,direction,category,description,amount,order_id,created_by)values(p_organization_id,p_date,'in','Pedido','Recebimento '||order_row.code||' · '||p_method,p_amount,p_order_id,auth.uid())returning id into cash_id;
insert into payments(organization_id,order_id,date,amount,method,cash_movement_id,created_by)values(p_organization_id,p_order_id,p_date,p_amount,p_method,cash_id,auth.uid())returning id into payment_id;
update orders set paid=paid+p_amount,balance=greatest(0,total-(paid+p_amount)),updated_by=auth.uid(),updated_at=now()where id=p_order_id;
insert into audit_events(organization_id,actor_id,action,entity_type,entity_id,summary,after_data)values(p_organization_id,auth.uid(),'payment','orders',p_order_id::text,'Registrou pagamento',jsonb_build_object('amount',p_amount,'method',p_method));return payment_id;end$$;
