export type Field={name:string;label:string;type?:"text"|"number"|"date"|"email"|"textarea"|"select";options?:string[];required?:boolean};
export type Area="products"|"inventory"|"clients"|"production"|"content"|"partners"|"finance";
export const configs:Record<Area,{table:string;title:string;eyebrow:string;description:string;fields:Field[];columns:string[]}>={
products:{table:"products",title:"Produtos & precificação",eyebrow:"Catálogo",description:"Custos completos, margem e preços da Lamelle 3D.",columns:["name","grams","print_minutes","multiplier","active"],fields:[{name:"name",label:"Nome",required:true},{name:"occasion",label:"Ocasião"},{name:"grams",label:"Gramas",type:"number"},{name:"print_minutes",label:"Minutos de impressão",type:"number"},{name:"work_minutes",label:"Minutos do seu trabalho",type:"number"},{name:"supplies",label:"Insumos (R$)",type:"number"},{name:"packaging",label:"Embalagem (R$)",type:"number"},{name:"multiplier",label:"Multiplicador",type:"number"},{name:"model_license",label:"Licença do modelo"}]},
inventory:{table:"inventory_items",title:"Estoque",eyebrow:"Materiais",description:"Filamentos, embalagens e insumos com movimentos auditáveis.",columns:["name","type","color","quantity","minimum","unit"],fields:[{name:"name",label:"Nome",required:true},{name:"type",label:"Tipo",type:"select",options:["Filamento","Insumo","Embalagem"],required:true},{name:"category",label:"Categoria"},{name:"color",label:"Cor"},{name:"unit",label:"Unidade",required:true},{name:"quantity",label:"Quantidade inicial",type:"number"},{name:"minimum",label:"Estoque mínimo",type:"number"},{name:"unit_cost",label:"Custo unitário",type:"number"}]},
clients:{table:"clients",title:"Clientes",eyebrow:"Relacionamento",description:"Contatos e histórico comercial em um único lugar.",columns:["name","phone","email","instagram"],fields:[{name:"name",label:"Nome",required:true},{name:"phone",label:"Telefone"},{name:"email",label:"E-mail",type:"email"},{name:"instagram",label:"Instagram"},{name:"notes",label:"Notas",type:"textarea"}]},
production:{table:"production_jobs",title:"Agenda & produção",eyebrow:"Bambu Lab A1",description:"Fila priorizada por pagamento e data do evento.",columns:["name","kind","event_date","quantity","planned_hours","status"],fields:[{name:"name",label:"Trabalho",required:true},{name:"kind",label:"Tipo",type:"select",options:["order","portfolio","stock"],required:true},{name:"event_date",label:"Data do evento",type:"date"},{name:"quantity",label:"Quantidade",type:"number"},{name:"planned_hours",label:"Horas previstas",type:"number"},{name:"status",label:"Status",type:"select",options:["Planejado","Imprimindo","Pausado","Concluído","Cancelado"]}]},
content:{table:"content_items",title:"Conteúdo",eyebrow:"Instagram",description:"Calendário editorial, salvamentos e mensagens no direct.",columns:["title","week","format","publish_date","status","saves","directs"],fields:[{name:"title",label:"Pauta",required:true},{name:"week",label:"Semana",type:"number"},{name:"format",label:"Formato",type:"select",options:["Foto","Reels","Carrossel","Stories"]},{name:"cta",label:"CTA"},{name:"publish_date",label:"Publicação",type:"date"},{name:"status",label:"Status",type:"select",options:["Ideia","Produzindo","Agendado","Publicado"]},{name:"reach",label:"Alcance",type:"number"},{name:"saves",label:"Salvamentos",type:"number"},{name:"directs",label:"Directs",type:"number"}]},
partners:{table:"partners",title:"Parceiros",eyebrow:"Grande Vitória",description:"Prospecção e relacionamento com negócios locais.",columns:["name","type","contact","status","last_contact"],fields:[{name:"name",label:"Nome",required:true},{name:"type",label:"Tipo",type:"select",options:["Buffet infantil","Doceria","Cerimonialista","Loja de festa","Fotógrafo","Outro"]},{name:"contact",label:"Contato"},{name:"status",label:"Status",type:"select",options:["A visitar","Visitado","Amostra entregue","Parceria ativa","Sem interesse"]},{name:"last_contact",label:"Último contato",type:"date"},{name:"notes",label:"Notas",type:"textarea"}]},
finance:{table:"cash_movements",title:"Fluxo de caixa",eyebrow:"Financeiro",description:"Entradas, saídas, recebíveis e resultado mensal.",columns:["date","direction","category","description","amount"],fields:[{name:"date",label:"Data",type:"date",required:true},{name:"direction",label:"Tipo",type:"select",options:["in","out"],required:true},{name:"category",label:"Categoria",required:true},{name:"description",label:"Descrição",required:true},{name:"amount",label:"Valor",type:"number",required:true}]}
};
export const numericFields=new Set(["grams","print_minutes","work_minutes","supplies","packaging","multiplier","quantity","minimum","unit_cost","planned_hours","week","reach","saves","directs","amount"]);
